# Generated by Django 4.1.4 on 2024-09-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_rename_links_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='usable_times',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='used_times',
            field=models.IntegerField(default=0),
        ),
    ]
