# Generated by Django 4.1.4 on 2024-09-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AppleMusic', 'AppleMusic'), ('AppleOne', 'AppleOne'), ('Spotify', 'Spotify')], max_length=100)),
                ('duration', models.CharField(choices=[('2 month', '2 month'), ('4 month', '4 month'), ('6 month', '6 month')], max_length=100)),
                ('code', models.CharField(max_length=255)),
                ('link', models.TextField(max_length=2000)),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
