# Generated by Django 4.1.4 on 2024-10-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_description_order_link_order_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='description',
            new_name='input',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Done', 'Done'), ('In-process', 'In-process'), ('Cancelled', 'Cancelled')], default='New', max_length=15),
        ),
    ]
