# Generated by Django 4.1.4 on 2024-10-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_description_order_input_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='response',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
