# Generated by Django 4.1.4 on 2024-10-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Done', 'Done'), ('In-process', 'In-process'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], default='New', max_length=15),
        ),
    ]
